service: fg-api

# Pin service to only deploy with a specific Serverless version
frameworkVersion: '2'

# AWS config parameters
provider:
  name: aws
  runtime: python3.7

  stackName: fotower-gallery
  apiName: fotower-gallery

  stage: dev
  region: ap-southeast-2

  apiGateway:
    metrics: true

# Each function includes the files it needs
package:
  exclude:
    - apis/**
  individually: true

# Link to 3 files containing endpoint-specific functions
functions:
  - '${file(apis/feed/feed.serverless.yml)}'
  - '${file(apis/pictures/pictures.serverless.yml)}'
  - '${file(apis/users/users.serverless.yml)}'
