create-user:
  handler: create_user.lambda_handler
  events:
    - http: 
        path: users
        method: post
        integration: lambda
        cors: true

delete-user:
  handler: delete_user.lambda_handler
  events:
    - http: 
        path: users/{id}
        method: delete
        integration: lambda
        cors: true

fetch-user:
  handler: fetch_user.lambda_handler
  events:
    - http: 
        path: users/{id}
        method: get
        integration: lambda
        cors: true

update-user:
  handler: update_user.lambda_handler
  events:
    - http: 
        path: users/{id}
        method: put
        integration: lambda
        cors: true