delete-user:
  name: fg-delete-user
  description: Remove a user, this operation is destructive.
  handler: apis/users/delete_user.lambda_handler
  package:
    include:
      - apis/users/delete_user.py
  events:
    - http: 
        path: users/{username}
        method: delete
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer

fetch-user:
  name: fg-fetch-user
  description: Fetch user information.
  handler: apis/users/fetch_user.lambda_handler
  package:
    include:
      - apis/users/fetch_user.py
  events:
    - http: 
        path: users/{username}
        method: get
        cors: true

update-user:
  name: fg-update-user
  description: Update a given user's information.
  handler: apis/users/update_user.lambda_handler
  package:
    include:
      - apis/users/update_user.py
  events:
    - http: 
        path: users/{username}
        method: put
        cors: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiGatewayAuthorizer